FROM php:8.4.1-fpm-alpine AS vendor

WORKDIR /app

RUN apk add --no-cache \
    git \
    icu-dev \
    libpng-dev \
    libzip-dev \
    oniguruma-dev \
    unzip \
    zip \
  && docker-php-ext-install \
    intl \
    mbstring \
    pdo_mysql \
    zip

COPY --from=composer:2.7.2 /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

FROM php:8.4.1-fpm-alpine

WORKDIR /var/www/backend

RUN apk add --no-cache \
    bash \
    curl \
    git \
    icu-dev \
    libpng-dev \
    libzip-dev \
    oniguruma-dev \
    unzip \
    zip \
  && docker-php-ext-install \
    intl \
    mbstring \
    pdo_mysql \
    zip

COPY --from=composer:2.7.2 /usr/bin/composer /usr/bin/composer
COPY --from=vendor /app/vendor ./vendor
COPY . .

EXPOSE 9000

CMD ["php-fpm"]
